server:
  port: 5001
spring:
  application:
    name: FASTGO-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: fastgo-zuul-gateway-5001.com #为当前服务器添加实例的标识
    prefer-ip-address: true
zuul:
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
  routes:
    plat:
      path: /plat/**
      service-id: fastgo-plat